site_name: Ed's Docs
site_url: https://edlai.github.io/
nav:
    - Home: 'index.md'
    - 'Engineering':
        - 'Linux Distribution': 'linux-distribution.md'
        - 'Development Tools': 'development-tools.md'
        - 'Embedded Linux': 'embedded-linux.md'
        - 'Computer Networks': 'computer-networks.md'
        - 'Digital Signal Processing': 'digital-signal-processing.md'
        - 'Operating Systems': 'operating-systems.md'
    - 'Education':
        - 'Qualitative Research': 'qualitative-research.md'
        - 'Quantitative Research': 'quantitative-research.md'
    - 'Motivation':
        - 'Painting': 'painting.md'
        - 'Traveling': 'traveling.md'
theme:
  name: material
  font:
    text: Roboto
  features:
    - navigation.tabs