site_name: Ed's Wiki  🦉
site_url: https://edlai.github.io/
nav:
    - Home:
        - 'About Me': 'index.md'
        - 'About Here': '/#about-here'
        - 'Academic Background': '/#academic-background'
        - 'Work Experience': '/#work-experience'
        - 'Technician Certificate': '/#technician-certificate'
        - 'Technician Training': '/#technician-training'
    - 'Engineering':
        - 'Development Tools':
          - 'Softwares Tools': 'dev/softwares/index.md'
          - 'Accessories': 'dev/accessories/index.md'
          - 'Networking Equipments': 'dev/equipments/index.md'
          - 'Automation and Crawler': 'dev/auto/index.md'
          - 'Diagnostic Tools': 'dev/diag/index.md'
          - 'Performance Measurement': 'dev/perf/index.md'
          - 'Git and Build Machine': 'dev/git/index.md'
          - 'Docker and Macvlan': 'dev/docker/index.md'
          - 'Documentation': 'dev/doc/index.md'
          - 'Programmer Skills': 'dev/prog/index.md'
          - 'Extending Python with C': 'dev/python/index.md'
          - 'Mass Production': 'dev/mass/index.md'
#         - 'QCOM QxDM and MTK Catcher': 'dev/diag/index.md'
#         - 'IxVeriWave and OctoBox': 'dev/wifi/index.md'
#         - 'SDR and CMW500': 'dev/bss/index.md'
#         - 'Testbed Setup': 'dev/testbed/index.md'
#       - 'Leadership': 'leadership.md'
        - 'Embedded Linux':
          - 'Buildroot': 'embedded/buildroot/index.md'
          - 'OpenWRT': 'embedded/openwrt/index.md'
        - 'Linux Distribution':
          - 'Debian 10.10': 'distro/debian10/index.md'
        - 'Computer Networks':
          - 'Application Layer':
            - 'Hypertext Transfer Protocol(HTTP)': 'net/hypertext-transfer-protocol/index.md'
            - 'File Transfer Protocol (FTP)': 'net/file-transfer-protocol/index.md'
            - 'Simple Mail Transfer Protocol and Post Office Protocol - Version 3 (IMAP/POP3)': 'net/simple-mail-transfer-protocol-and-post-office-protocol/index.md'
        - 'Digital Signal Processing':
          - 'Voice Processing':
            - 'Discrete-Time Processing' : 'dsp/discrete-time-processing/index.md'
            - 'Moving Average and Backward System' : 'dsp/moving-average-and-backward-system/index.md'
          - 'Spectrum Analysis':
            - 'Window Size and the Spectrogram' : 'dsp/window-size-and-the-spectrogram/index.md'
        - 'Operating Systems':
          - 'An Assembler Compiler': 'os/assembler-compiler/index.md'
        - 'Man-Machine Interfaces':
          - 'Industry Standard Architecture (ISA)': 'io/isa/index.md'
          - 'Peripheral Component Interconnect (PCI)': 'io/pci/index.md'
          - 'Parallel Port Device (LPT) and Linux Device Driver': 'io/ldd/index.md'
          - 'General Purpose Input Output (GPIO)': 'io/gpio/index.md'
          - 'Inter-Integrated Circuit (I2C)': 'io/i2c/index.md'
        - 'Television Engineering':
          - 'Multimedia Player': 'tv/player/index.md'
          - 'Digital Vedio Conversion - MPEG-1': 'tv/mpeg1/index.md'
#         - 'Digital Vedio Conversion - MPEG2, MPEG3, MPEG4(DivX)': 'tv/mpeg2/index.md'
        - 'Miscellaneous':
          - 'Misc': 'misc/index.md'
    - 'Education':
        - 'Introduction': 'edu/index.md'
        - 'Thesis': 'edu/thesis/index.md'
        - 'English': 'edu/english/index.md'
        - 'Information Education': 'edu/information-edu/index.md'
        - 'Qualitative Research': 'edu/qualitative-research/index.md'
        - 'Quantitative Research': 'edu/quantitative-research/index.md'
    - 'Collection':
        - 'Collections': 'collections/index.md'
#    - 'Motivation':
#        - 'Painting': 'motivation/painting.md'
    - 'Traveling':
        - 'Trip': 'traveling/trip.md'
        - 'Tour': 'traveling/tour.md'
        - 'Photos': 'photos/index.md'

theme:
  name: material
  font:
    text: Roboto
  features:
    - navigation.tabs
#  custom_dir: mkdocs-rtd-lightbox

markdown_extensions:
#  - lightbox
#  - extra
  - pymdownx.snippets
  - pymdownx.tabbed
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
    - search
    - mermaid2:

extra_javascript:
    - https://unpkg.com/mermaid/dist/mermaid.min.js
