site_name: Ed's Personal Wiki
site_url: https://edlai.github.io/
nav:
    - Home: 'index.md'
    - 'Engineering':
        - 'Linux Distribution':
          - 'Debian': 'distro/debian/index.md'
        - 'Development Tools':
          - 'Softwares Tools': 'dev/softwares/index.md'
          - 'Accessories': 'dev/accessories/index.md'
          - 'Equipments': 'dev/equipments/index.md'
        - 'Embedded Linux': 
          - 'Buildroot': 'embedded/buildroot/index.md'
          - 'OpenWRT': 'embedded/openwrt/index.md'
        - 'Computer Networks':
          - 'Application Layer':
            - 'Hypertext Transfer Protocol(HTTP)': 'net/hypertext-transfer-protocol/index.md'
            - 'File Transfer Protocol (FTP)': 'net/file-transfer-protocol/index.md'
            - 'Simple Mail Transfer Protocol and Post Office Protocol - Version 3 (IMAP/POP3)': 'net/simple-mail-transfer-protocol-and-post-office-protocol/index.md'
        - 'Digital Signal Processing':
          - 'Voice Processing':
            - 'Discrete-Time Processing' : 'dsp/discrete-time-processing/index.md'
            - 'Moving Average and Backward System' : 'dsp/moving-average-and-backward-system/index.md'
          - 'Spectrum Analysis':
            - 'Window Size and the Spectrogram' : 'dsp/window-size-and-the-spectrogram/index.md'
        - 'Operating Systems': 
          - 'An Assembler Compiler': 'os/assembler-compiler/index.md'
        - 'Man-Machine Interfaces': 
          - 'Industry Standard Architecture (ISA)': 'io/isa/index.md'
          - 'Peripheral Component Interconnect (PCI)': 'io/pci/index.md'
          - 'Parallel Port Device (LPT) and Linux Device Driver': 'io/ldd/index.md'
          - 'General Purpose Input Output (GPIO)': 'io/gpio/index.md'
          - 'Inter-Integrated Circuit (I2C)': 'io/i2c/index.md'
        - 'Television Engineering': 
          - 'Multimedia Player': 'tv/player/index.md'
          - 'Digital Vedio Conversion - MPEG-1': 'tv/mpeg1/index.md'
#         - 'Digital Vedio Conversion - MPEG2, MPEG3, MPEG4(DivX)': 'tv/mpeg2/index.md'
        - 'Miscellaneous':
          - 'Misc': 'misc/index.md'
    - 'Education':
        - 'Qualitative Research': 'qualitative-research.md'
        - 'Quantitative Research': 'quantitative-research.md'
    - 'Collection':
        - 'Collections': 'collections/index.md'
    - 'Motivation':
        - 'Traveling': 'traveling.md'
        - 'Painting': 'painting.md'

theme:
  name: material
  font:
    text: Roboto
  features:
    - navigation.tabs
