site_name: Ed's Wiki  🦉
site_url: https://edlai.github.io/
nav:
    - Home:
        - 'About Me': 'index.md'
        - 'About Here': '/#about-here'
        - 'Academic Background': '/#academic-background'
        - 'Work Experience': '/#work-experience'
        - 'Technician Certificate': '/#technician-certificate'
        - 'Technician Training': '/#technician-training'
    - 'Engineering':
        - 'Development Tools':
          - 'Softwares Tools': 'engineer/dev/softwares/index.md'
          - 'Accessories': 'engineer/dev/accessories/index.md'
          - 'Networking Equipments': 'engineer/dev/equipments/index.md'
          - 'Automation and Crawler': 'engineer/dev/auto/index.md'
          - 'Diagnostic Tools': 'engineer/dev/diag/index.md'
          - 'Performance Measurement': 'engineer/dev/perf/index.md'
          - 'Git Repo and Build Machine': 'engineer/dev/git/index.md'
          - 'Docker and Macvlan': 'engineer/dev/docker/index.md'
          - 'Documentation': 'engineer/dev/doc/index.md'
          - 'Programmer Skills': 'engineer/dev/prog/index.md'
          - 'Extending Python with C': 'engineer/dev/python/index.md'
#         - 'QCOM QxDM and MTK Catcher': 'dev/diag/index.md'
#         - 'IxVeriWave and OctoBox': 'dev/wifi/index.md'
#         - 'SDR and CMW500': 'dev/bss/index.md'
#         - 'Testbed Setup': 'dev/testbed/index.md'
#       - 'Leadership': 'leadership.md'
        - 'Linux Kernel':
          - 'Rebuild Kernel': 'engineer/kernel/rebuild/index.md'
        - 'Embedded Linux':
          - 'SDK Framework':
            - 'Buildroot': 'engineer/embedded/buildroot/index.md'
            - 'OpenWRT': 'engineer/embedded/openwrt/index.md'
          - 'Application':
            - 'Surveillance Camera': 'engineer/embedded/cam/cloud/index.md'
          - 'Lifetime Measurement':
            - 'Flash MTD Lifetime': 'engineer/dev/lifetime/index.md'
        - 'Celluar Network':
          - 'Amarisoft SDR': 'engineer/cell/sdr/index.md'
        - 'Computer Networks':
          - 'Application Layer':
            - 'Hypertext Transfer Protocol(HTTP)': 'engineer/net/hypertext-transfer-protocol/index.md'
            - 'File Transfer Protocol (FTP)': 'engineer/net/file-transfer-protocol/index.md'
            - 'Simple Mail Transfer Protocol and Post Office Protocol - Version 3 (IMAP/POP3)': 'engineer/net/simple-mail-transfer-protocol-and-post-office-protocol/index.md'
        - 'Digital Signal Processing':
          - 'Voice Processing':
            - 'Discrete-Time Processing' : 'engineer/dsp/discrete-time-processing/index.md'
            - 'Moving Average and Backward System' : 'engineer/dsp/moving-average-and-backward-system/index.md'
          - 'Spectrum Analysis':
            - 'Window Size and the Spectrogram' : 'engineer/dsp/window-size-and-the-spectrogram/index.md'
        - 'Image Processing':
            - 'Grayscale': 'engineer/dip/js/grayscale/index.md'
            - 'Monochrome': 'engineer/dip/js/monochrome/index.md'
            - 'Negative Film': 'engineer/dip/js/negative/index.md'
            - 'Colorbar': 'engineer/dip/js/colorbar/index.md'
            - 'Text Picture': 'engineer/dip/js/text/index.md'
            - 'Mirror': 'engineer/dip/js/mirror/index.md'
            - 'Image Resizer': 'engineer/dip/py/resize/index.md'
        - 'Operating Systems':
          - 'An Assembler Compiler': 'engineer/os/assembler-compiler/index.md'
        - 'Man-Machine Interfaces':
          - 'Industry Standard Architecture (ISA)': 'engineer/io/isa/index.md'
          - 'Peripheral Component Interconnect (PCI)': 'engineer/io/pci/index.md'
          - 'Parallel Port Device (LPT) and Linux Device Driver': 'engineer/io/ldd/index.md'
          - 'General Purpose Input Output (GPIO)': 'engineer/io/gpio/index.md'
          - 'Inter-Integrated Circuit (I2C)': 'engineer/io/i2c/index.md'
        - 'Television Engineering':
          - 'Multimedia Player': 'engineer/tv/player/index.md'
          - 'Digital Vedio Conversion - MPEG-1': 'engineer/tv/mpeg1/index.md'
#         - 'Digital Vedio Conversion - MPEG2, MPEG3, MPEG4(DivX)': 'tv/mpeg2/index.md'
        - 'Miscellaneous':
          - 'Misc': 'engineer/misc/index.md'
    - 'Education':
        - 'Introduction': 'edu/index.md'
        - 'Thesis': 'edu/thesis/index.md'
        - 'English': 'edu/english/index.md'
        - 'Information Education': 'education/information-edu/index.md'
        - 'Qualitative Research': 'education/qualitative-research/index.md'
        - 'Quantitative Research': 'education/quantitative-research/index.md'
    - 'Collection':
        - 'Collections': 'collections/index.md'
#    - 'Motivation':
#        - 'Painting': 'motivation/painting.md'
    - 'Traveling':
        - 'Trip': 'traveling/trip.md'
        - 'Tour': 'traveling/tour.md'
    - 'Photos': 'photos/index.md'

theme:
  name: material
  font:
    text: Roboto
  features:
    - navigation.tabs
#  custom_dir: mkdocs-rtd-lightbox

markdown_extensions:
#  - lightbox
#  - extra
  - pymdownx.snippets
  - pymdownx.tabbed
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
    - search
    - mermaid2:

extra_javascript:
    - https://unpkg.com/mermaid/dist/mermaid.min.js
