site_name: Ed's Personal Wiki
site_url: https://edlai.github.io/
nav:
    - Home: 'index.md'
    - 'Engineering':
        - 'Linux Distribution':
          - 'Debian': 'distro/debian/index.md'
        - 'Development Tools':
          - 'Softwares Tools': 'dev/softwares/index.md'
          - 'Accessories': 'dev/accessories/index.md'
        - 'Embedded Linux': 
          - 'Buildroot': 'embedded/buildroot/index.md'
          - 'OpenWRT': 'embedded/openwrt/index.md'
        - 'Computer Networks':
          - 'Application Layer':
            - 'Hypertext Transfer Protocol(HTTP)': 'net/hypertext-transfer-protocol/index.md'
            - 'File Transfer Protocol (FTP)': 'net/file-transfer-protocol/index.md'
            - 'Simple Mail Transfer Protocol and Post Office Protocol - Version 3 (IMAP/POP3)': 'net/simple-mail-transfer-protocol-and-post-office-protocol/index.md'
        - 'Digital Signal Processing':
          - 'Voice Processing':
            - 'Discrete-Time Processing' : 'dsp/discrete-time-processing/index.md'
            - 'Moving Average and Backward System' : 'dsp/moving-average-and-backward-system/index.md'
          - 'Spectrum Analysis':
            - 'Window Size and the Spectrogram' : 'dsp/window-size-and-the-spectrogram/index.md'
        - 'Operating Systems': 
          - 'Compiler':
            - 'An Assembler Compiler': 'os/assembler-compiler/index.md'
        - 'Miscellaneous':
          - 'Misc': 'misc/index.md'
    - 'Education':
        - 'Qualitative Research': 'qualitative-research.md'
        - 'Quantitative Research': 'quantitative-research.md'
    - 'Motivation':
        - 'Painting': 'painting.md'
        - 'Traveling': 'traveling.md'
theme:
  name: material
  font:
    text: Roboto
  features:
    - navigation.tabs
