site_name: Ed's Learning Portfolios
site_url: https://edlai.github.io/
nav:
    - Home:
       - 'About Me': 'index.md'
       - 'About Here': 'home/here.md'
    - 'Engineering':
        - 'Introduction': 'engineering/index.md'
        - 'Prior Knowledge (Courses)':
          - 'Undergraduate': 'engineering/courses/undergraduate/index.md'
          - 'Moocs (Autodidacticism)': 'engineering/courses/moocs/index.md'
#          - 'Autodidacticism': 'engineering/courses/autodidacticism/index.md'
#          - 'Image Processing':
#              - 'Grayscale': 'engineering/courses/undergraduate/dip/grayscale/index.md'
#              - 'Monochrome': 'engineering/courses/undergraduate/dip/monochrome/index.md'
#              - 'Negative Film': 'engineering/courses/undergraduate/dip/negative/index.md'
#              - 'Colorbar': 'engineering/courses/undergraduate/dip/colorbar/index.md'
#              - 'Text Picture': 'engineering/courses/undergraduate/dip/text/index.md'
#              - 'Mirror': 'engineering/courses/undergraduate/dip/mirror/index.md'
#              - 'Image Resizer': 'engineering/courses/undergraduate/dip/resize/index.md'
#          - 'Reports':
#            - 'Computer Networks':
#              - 'Hypertext Transfer Protocol(HTTP)': 'engineering/courses/undergraduate/net/hypertext-transfer-protocol/index.md'
#              - 'File Transfer Protocol (FTP)': 'engineering/courses/undergraduate/net/file-transfer-protocol/index.md'
#              - 'Simple Mail Transfer Protocol and Post Office Protocol - Version 3 (IMAP/POP3)': 'engineering/courses/undergraduate/net/simple-mail-transfer-protocol-and-post-office-protocol/index.md'
#            - 'Digital Signal Processing':
#              - 'Voice Processing':
#                - 'Discrete-Time Processing' : 'engineering/courses/undergraduate/dsp/discrete-time-processing/index.md'
#                - 'Moving Average and Backward System' : 'engineering/courses/undergraduate/dsp/moving-average-and-backward-system/index.md'
#              - 'Spectrum Analysis':
#                - 'Window Size and the Spectrogram' : 'engineering/courses/undergraduate/dsp/window-size-and-the-spectrogram/index.md'
#            - 'Operating Systems':
#              - 'An Assembler Compiler': 'engineering/courses/undergraduate/os/assembler-compiler/index.md'
#            - 'Man-Machine Interfaces':
#              - 'Industry Standard Architecture (ISA)': 'engineering/courses/undergraduate/io/isa/index.md'
#              - 'Peripheral Component Interconnect (PCI)': 'engineering/courses/undergraduate/io/pci/index.md'
#              - 'Parallel Port Device (LPT) and Linux Device Driver': 'engineering/courses/undergraduate/io/ldd/index.md'
#              - 'General Purpose Input Output (GPIO)': 'engineering/courses/undergraduate/io/gpio/index.md'
#              - 'Inter-Integrated Circuit (I2C)': 'engineering/courses/undergraduate/io/i2c/index.md'
#            - 'Television engineeringing':
#              - 'Multimedia Player': 'engineering/courses/undergraduate/tv/player/index.md'
#              - 'Digital Vedio Conversion - MPEG-1': 'engineering/courses/undergraduate/tv/mpeg1/index.md'
#              - 'Digital Vedio Conversion - MPEG2, MPEG3, MPEG4(DivX)': 'tv/mpeg2/index.md'
#              - ''
        - 'Researching':
          - 'Reading Papers': 'engineering/research/papers/index.md'
          - 'Specification': 'engineering/rese
          arch/specification/index.md'
#            - '3GPP': ''
#            - 'IEEE': ''
#            - 'RFC': ''
#            - 'Broadband Forum': ''
#            - 'Wi-Fi Alliance': ''
#            - 'Connectivity Standards Alliance': ''
          - 'Documentation':
             - 'Markdown': 'engineering/research/documentation/markdown/index.md'
             - 'reStructuredText': 'engineering/research/documentation/restructuredtext/index.md'
             - 'Latex': 'engineering/research/documentation/xelatex/index.md'
             - 'UML': 'engineering/research/documentation/uml/index.md'
#         - 'Master Thesis'
        - 'Development':
          - 'Softwares Tools': 'engineering/development/softwares/index.md'
          - 'Accessories': 'engineering/development/accessories/index.md'
          - 'Automation and Crawler': 'engineering/development/auto/index.md'
#          - 'Git Repo and Build Machine': 'engineering/dev/git/index.md'
#          - 'Docker and Macvlan':
#            - 'DockerFile': 'engineering/dev/docker/file/index.md'
#            - 'Docker Compose': 'engineering/dev/docker/compose/index.md'
#            - 'Macvlan': 'engineering/dev/docker/macvlan/index.md'
          - 'Programming Languages':
            - 'Linux C':
              - 'GCC Compiler History': 'engineering/development/programming/linux_c/env_toolchain.md'
              - 'Debugging Skills': 'engineering/development/programming/linux_c/debug_skill.md'
#             - 'Memory Layout': 'engineering/development/programming/linux_c/memory_layout.md'
#             - 'Event Loop': 'engineering/development/programming/linux_c/event_loop.md'
              - 'State Machine': 'engineering/development/programming/linux_c/state_machine.md'
              - 'Function Argument': 'engineering/development/programming/linux_c/function_call.md'
              - 'System Time': 'engineering/development/programming/linux_c/system_time.md'
              - 'System Timer': 'engineering/development/programming/linux_c/system_timer.md'
              - 'String Manipulation': 'engineering/development/programming/linux_c/string_manipulation.md'
#             - 'Reactor pattern': 'engineering/prog/linux_c/reactor_pattern.md'
#             - 'MQTT': 'engineering/prog/linux_c/comm_mqtt.md'
#             - 'Inotify': 'engineering/prog/linux_c/inotify.md'
#             - 'Object-Oriented': 'engineering/prog/linux_c/oo.md'
#         - 'Resources': 'engineering/prog/linux_c/resources.md'
#            - 'C Version': 'engineering/dev/prog/linux_c/memory_layout.md'
#            - 'Memory Layout': 'engineering/dev/prog/linux_c/memory_layout.md'
#            - 'Fixed Width of Integer': 'engineering/dev/prog/linux_c/memory_layout.md'

#            - 'Linux C (Advance)': 'engineering/dev/prog/c_adv/index.md'
#            - 'Python with C': 'engineering/dev/python/index.md'
#         - 'Conversation Skills':
#           - 'Lee Books':
#           - 'TOEFL': 'engineering/dev/conv/toefl/index.md'
#         - 'QCOM QxDM and MTK Catcher': 'dev/diag/index.md'
#         - 'IxVeriWave and OctoBox': 'dev/wifi/index.md'
#         - 'SDR and CMW500': 'dev/bss/index.md'
#         - 'Testbed Setup': 'dev/testbed/index.md'
#         - 'Leadership': 'leadership.md'
          - 'Scripting Language':
            - 'TCL':
              - 'Contact Manager': 'engineering/development/scripting/tcl/contactManager/index.md'
              - 'Execution Logger': 'engineering/development/scripting/tcl/executionLogger/index.md'
              - 'Simple Calculator': 'engineering/development/scripting/tcl/simpleCalculator/index.md'
#             - 'Wap Phone Emulator': 'engineering/development/scripting/tcl/wapPhoneEmulator/index.md'
            - 'Perl':
              - 'Quiz': 'engineering/development/scripting/pl/quiz/index.md'
              - 'Dictionary': 'engineering/development/scripting/pl/dictionary/index.md'
#           - 'Python':
#            - 'AES': 'engineering/script/py/aes/index.md'
#            - 'CTYPE': 'engineering/script/py/ctype/index.md'
#            - 'Request': 'engineering/script/py/request/index.md'
#            - 'Selenium': 'engineering/script/py/selenium/index.md'
          - 'Embedded Linux':
            - 'Buildroot SDK Framework': 'engineering/development/embedded/buildroot/index.md'
            - 'OpenWRT SDK Framework': 'engineering/development/embedded/openwrt/index.md'
            - 'Surveillance Camera': 'engineering/development/embedded/camera/cloud/index.md'
#           - 'Production':
#            - 'Flash MTD Endurance': 'engineering/embedded/endurance/index.md'
          - 'Linux Kernel':
            - 'Rebuild Linux Kernel': 'engineering/development/kernel/rebuild/index.md'
        - 'Verification':
          - 'Performance Measurement':
            - 'Networking Performance': 'engineering/verification/perf/index.md'
        - 'Software Release':
#         - 'Redmine'
          - 'Git':
            - 'Gitlab': 'engineering/development/release/gitlab/index.md'
            - 'Azure': 'engineering/development/release/gitlab/index.md'
          - 'DevOps':
            - 'CI/CD': 'engineering/development/release/cicd/index.md'
        - 'Debugging':
          - 'Diagnostic Tools':
            - 'Wireless Sniffer - Wireshark': 'engineering/debugging/diagnostic//sniffer/index.md'
            - 'Remote Capturer - rpcapd': 'engineering/debugging/diagnostic//rpcapd/index.md'
            - 'Networking Sniffer - tcpdump': 'engineering/debugging/diagnostic//tcpdump/index.md'
            - 'Networking Sniffer - wireshark': 'engineering/debugging/diagnostic//wireshark/index.md'
#         - 'Duplication'
        - 'Instrument':
          - 'Cellular Network':
            - 'Software Defined Network': 'engineering/instrument/cellular/sdr/index.md'
#           - 'R&S CMW500':
#         - 'Wi-Fi Network':
#           - 'IxVeriWave':
        - 'Teamwork':
          - 'Character': 'engineering/teamwork/character/index.md'
        - 'Motivation':
          - 'Trip': 'engineering/motivation/trip/photo/index.md'
#        - 'Miscellaneous':
#          - 'Misc': 'engineering/misc/index.md'
    - 'Education':
        - 'Intro.': 'education/index.md'
        - 'Courses':
          - 'Postgraduate': 'education/courses/postgraduate/index.md'
        - 'Research':
          - 'Reading Papers': 'education/research/papers/index.md'
          - 'My Master Thesis': 'education/research/thesis/index.md'
#        - 'Introduction': 'education/index.md'
#        - 'English': 'education/english/index.md'
#        - 'Information Education': 'education/information-edu/index.md'
#        - 'Qualitative Research': 'education/qualitative-research/index.md'
#        - 'Quantitative Research': 'education/quantitative-research/index.md'
    - 'Living':
      - 'Books': 'living/books.md'
      - 'Music': 'living/music.md'
      - 'Kids': 'living/kids.md'
#      - 'Collection': 'daily/collection.md'
#      - 'Vocabulary': 'daily/vocabulary.md'
#     - 'Motivation': 'daily/motivation.md'
#    - 'Motivation':
#        - 'Painting': 'motivation/painting.md'
#    - 'Traveling':
#        - 'Trip': 'traveling/trip.md'
#        - 'Tour': 'traveling/tour.md'
#    - 'Photos': 'photos/index.md'

theme:
  name: material
  font:
    text: Roboto
  features:
    - navigation.tabs
    - navigation.top
  logo: images/favicon.ico
  favicon: images/favicon.ico

#  custom_dir: mkdocs-rtd-lightbox

markdown_extensions:
  - toc:
      permalink: ⚓︎
  - pymdownx.snippets
  - pymdownx.tabbed
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.keys
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
    - search
    - mermaid2:

extra_javascript:
    - https://unpkg.com/mermaid/dist/mermaid.min.js
